export const CURRENCY_LIST = [
  { name: 'Euro (EUR)', value: 'EUR' },
  { name: 'United States Dollar (USD)', value: 'USD' },
  { name: 'British Pound Sterling (GBP)', value: 'GBP' },
  { name: 'Australian Dollar (AUD)', value: 'AUD' },
  { name: 'Canadian Dollar (CAD)', value: 'CAD' },
  { name: 'Swiss Franc (CHF)', value: 'CHF' },
  { name: 'Chinese Yuan (CNY)', value: 'CNY' },
  { name: 'Czech Republic Koruna (CZK)', value: 'CZK' },
  { name: 'Danish Krone (DKK)', value: 'DKK' },
  { name: 'Hong Kong Dollar (HKD)', value: 'HKD' },
  { name: 'Hungarian Forint (HUF)', value: 'HUF' },
  { name: 'Indian Rupee (INR)', value: 'INR' },
  { name: 'Japanese Yen (JPY)', value: 'JPY' },
  { name: 'Mexican Peso (MXN)', value: 'MXN' },
  { name: 'Malaysian Ringgit (MYR)', value: 'MYR' },
  { name: 'Norwegian Krone (NOK)', value: 'NOK' },
  { name: 'New Zealand Dollar (NZD)', value: 'NZD' },
  { name: 'Philippine Peso (PHP)', value: 'PHP' },
  { name: 'Polish Zloty (PLN)', value: 'PLN' },
  { name: 'Russian Ruble (RUB)', value: 'RUB' },
  { name: 'Swedish Krona (SEK)', value: 'SEK' },
  { name: 'Singapore Dollar (SGD)', value: 'SGD' },
  { name: 'Thai Baht (THB)', value: 'THB' },
  { name: 'Turkish Lira (TRY)', value: 'TRY' },
  { name: 'South African Rand (ZAR)', value: 'ZAR' }
]
